[[main]]
    identifier = "home"
    name = "主页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
    [main.params]
        icon = "tag"
